id: P007990
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:53:43.268416
source_metadata:
  id: bdr:W3CN6661
  title: བླ་མ་ལྔ་བཅུ་དང་རྩ་ལྟུང་བཅུ་བཞིའི་རྣམ་བཤད།
  author: ''
  volumes:
    dd374b10cb7e4b499c13b15cae2925fa:
      image_group_id: I3CN6663
      title: Volume 1 of bla ma lnga bcu dang rtsa ltung bcu bzhi'i rnam bshad/
      volume_number: 1
      total_pages: 400
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
