id: P007990
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6661
  title: བླ་མ་ལྔ་བཅུ་དང་རྩ་ལྟུང་བཅུ་བཞིའི་རྣམ་བཤད།
  author: ''
  volumes:
    596b2cce1b4a4faeb914fe84d00c497e:
      image_group_id: I3CN6663
      title: ''
      volume_number: 1
      total_pages: 400
ebook_metadata:
  title: བླ་མ་ལྔ་བཅུ་དང་རྩ་ལྟུང་བཅུ་བཞིའི་རྣམ་བཤད།
  author: ''
  sku: P007990
  cover: cover.jpg
  layers:
  - pagination
