id: IB699D836
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T11:34:03+00:00'
last_modified: '2022-06-09T08:23:04.180265+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6661
  title: བླ་མ་ལྔ་བཅུ་དང་རྩ་ལྟུང་བཅུ་བཞིའི་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    65A2:
      image_group_id: I3CN6663
      title: Volume 1 of bla ma lnga bcu dang rtsa ltung bcu bzhi'i rnam bshad/
      total_pages: 400
      order: 1
      base_file: 65A2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
